# Generated by Django 4.2.23 on 2025-07-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_exardproduct_alpha_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exardproduct',
            name='quantity',
            field=models.PositiveBigIntegerField(),
        ),
    ]
