# Generated by Django 4.2.23 on 2025-07-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
    ]
