# Generated by Django 4.2.23 on 2025-07-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_movie_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bap_number', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
