# Generated by Django 4.2.23 on 2025-08-01 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddUser',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
